import os

API_KEY = os.environ['IFQSYNC_DROPBOX_API_KEY']

API_SECRET = os.environ['IFQSYNC_DROPBOX_API_SECRET']

ACCESS_TOKEN_KEY = os.environ['IFQSYNC_DROPBOX_ACCESS_TOKEN_KEY']

ACCESS_TOKEN_SECRET = os.environ['IFQSYNC_DROPBOX_ACCESS_TOKEN_SECRET']

IFQ_USERNAME = os.environ['IFQSYNC_IFQ_USERNAME']

IFQ_PASSWORD = os.environ['IFQSYNC_IFQ_PASSWORD']

